version: 2.1

jobs:
  build:
    docker:
      - image: sceptreorg/sceptre-circleci:2.1.0

    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: v1-dependency-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry

  lint-and-unit-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.1.0

    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: v1-dependency-cache-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry

      - run:
          name: Linting
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: Unit Test
          command: |
            . venv/bin/activate
            mkdir test-reports
            make test

      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            make coverage

      - store_test_results:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: coverage.xml
          destination: coverage-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: coverage.xml
          destination: coverage-reports

  deploy-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.1.0

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: poetry install

      - run:
          name: Upload to PyPi
          command: |
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry publish --build -r test-pypi -u $PYPI_TEST_USER -p $PYPI_TEST_PASSWORD

  deploy-production:
    docker:
      - image: sceptreorg/sceptre-circleci:2.1.0

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: poetry install

      - run:
          name: Upload to PyPI
          command: poetry publish --build -u $PYPI_PROD_USER -p $PYPI_PROD_PASSWORD

workflows:
  test:
    jobs:
      - build
      - lint-and-unit-test:
          requires:
            - build
  tag:
    jobs:
      - deploy-test:
          context: sceptre-templates-context
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-production:
          context: sceptre-templates-context
          requires:
            - deploy-test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
